package zw.co.cassavasmartech.ecocashchatbotcore.model;

public enum Usecase {
    PIN_RESET,BUY_AIRTIME,SEND_MONEY,MERCHANT_PAYMENT,BILL_PAYMENT,SUBSCRIBER_STATEMENT,REGISTRATION,SEND_MONEY_TARIFF,BILLER_TARIFF,MERCHANT_TARIFF,BILLER_LOOKUP,MERCHANT_LOOKUP,TRANSACTION_REVERSAL
}
